# Generated by Django 3.0.8 on 2020-07-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laitaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipmentsincontract',
            table='EquipmentsinContract',
        ),
    ]
