# Generated by Django 3.0.8 on 2020-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentcompany',
            fields=[
                ('agentcompany_id', models.IntegerField(db_column='AgentCompany_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45, verbose_name='名称')),
                ('tel', models.BigIntegerField(blank=True, db_column='Tel', null=True, verbose_name='电话')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=80, null=True, verbose_name='地点')),
                ('representative', models.CharField(blank=True, db_column='Representative', max_length=45, null=True)),
            ],
            options={
                'verbose_name': '中介公司',
                'verbose_name_plural': '中介公司',
                'db_table': 'AgentCompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(db_column='Contract_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date', verbose_name='签订日期')),
                ('warranty', models.IntegerField(blank=True, db_column='Warranty', null=True, verbose_name='保修时长(月)')),
            ],
            options={
                'verbose_name': '销售合同',
                'verbose_name_plural': '销售合同',
                'db_table': 'Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.IntegerField(db_column='Equipment_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45, verbose_name='名称')),
                ('model', models.CharField(db_column='Model', max_length=45, verbose_name='型号')),
                ('price', models.CharField(blank=True, db_column='Price', max_length=45, null=True, verbose_name='进货价')),
                ('type', models.CharField(db_column='Type', max_length=45, verbose_name='类型')),
            ],
            options={
                'verbose_name': '设备清单',
                'verbose_name_plural': '设备清单',
                'db_table': 'Equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentsInContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbersold', models.IntegerField(blank=True, db_column='NumberSold', null=True)),
                ('pricesold', models.CharField(blank=True, db_column='PriceSold', max_length=45, null=True)),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
                'db_table': 'Equipments_in_Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.IntegerField(db_column='Hospital_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True, verbose_name='名称')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=45, null=True, verbose_name='地址')),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=45, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '医院列表',
                'verbose_name_plural': '医院列表',
                'db_table': 'Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.IntegerField(db_column='Producer_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45, verbose_name='名称')),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=45, null=True, verbose_name='电话')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=45, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '设备生产商',
                'verbose_name_plural': '设备生产商',
                'db_table': 'Producer',
                'managed': False,
            },
        ),
    ]
