# Generated by Django 3.0.8 on 2020-07-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laitaiapp', '0002_auto_20200725_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentsincontract',
            options={'managed': False, 'verbose_name': '所有合同汇总销售记录', 'verbose_name_plural': '所有合同汇总销售记录'},
        ),
    ]
